name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    outputs:
      artifacts-checksum: ${{ steps.binary.outputs.hashes }}
      container-image-name: ${{ steps.image.outputs.name }}
      container-image-digest: ${{ steps.image.outputs.digest }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
    - uses: goreleaser/goreleaser-action@v6
      id: goreleaser
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}

    # See:
    # https://slsa.dev/blog/2022/08/slsa-github-workflows-generic-ga
    # https://github.com/goreleaser/goreleaser-example-slsa-provenance/blob/master/.github/workflows/goreleaser.yml
    - name: generate binary hashes
      id: binary
      env:
        ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
      run: |
        set -euo pipefail
        checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
        echo "hashes=$(cat $checksum_file | base64 -w0)" >> "$GITHUB_OUTPUT"
    - name: generate image digest
      id: image
      env:
        ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
      run: |
        set -euo pipefail
        image_and_digest=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Docker Manifest") | .path')
        image=$(echo "${image_and_digest}" | cut -d'@' -f1 | cut -d':' -f1)
        digest=$(echo "${image_and_digest}" | cut -d'@' -f2)
        echo "name=$image" >> "$GITHUB_OUTPUT"
        echo "digest=$digest" >> "$GITHUB_OUTPUT"

  provenance:
    permissions:
      actions: read
      id-token: write
      packages: write
    needs: [release]
    uses: ./.github/workflows/provenance.yaml
    with:
      artifacts-checksum: ${{ needs.release.outputs.artifacts-checksum }}
      container-image-name: ${{ needs.release.outputs.container-image-name }}
      container-image-digest: ${{ needs.release.outputs.container-image-digest }}
