name: test
on:
  # pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel test //...

  test-release:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: check
    - uses: actions/setup-go@v5.1.0
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: |
          go.sum
          deps.bzl
    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: build --snapshot
